import { EsgPolicy, Audit, ComplianceIssue } from "./types";

export const MOCK_POLICIES: EsgPolicy[] = [
  {
    id: 1,
    title: "Code of Business Conduct & Integrity",
    description: "Our core ethical parameters outlining compliance with local anti-bribery, ethics, and standard operational laws.",
    category: "governance",
    version: "2.3",
    effectiveDate: new Date(Date.now() - 60 * 24 * 3600 * 1000),
    reviewDate: null,
    createdById: "usr_admin",
    createdAt: new Date(),
  },
  {
    id: 2,
    title: "Zero Single-Use Plastic Directive",
    description: "Internal company directive banning the stocking, purchase, and provisioning of single-use plastics inside corporate facilities.",
    category: "environmental",
    version: "1.0",
    effectiveDate: new Date(Date.now() - 45 * 24 * 3600 * 1000),
    reviewDate: null,
    createdById: "usr_manager",
    createdAt: new Date(),
  },
  {
    id: 3,
    title: "Supplier Diversity & Inclusion Charter",
    description: "A framework prioritizing minority, woman, and veteran-owned vendors throughout corporate procurement operations.",
    category: "social",
    version: "1.2",
    effectiveDate: new Date(Date.now() - 30 * 24 * 3600 * 1000),
    reviewDate: null,
    createdById: "usr_admin",
    createdAt: new Date(),
  },
];

export const MOCK_AUDITS: Audit[] = [
  {
    id: 1,
    title: "Q1 Governance & Compliance Check",
    scope: "Internal audits of policy logs, disclosures and risk registers.",
    auditorName: "Auditor User",
    auditDate: new Date(Date.now() - 30 * 24 * 3600 * 1000),
    status: "completed",
    findingsCount: 1,
    rating: "Excellent",
    reportUrl: "https://utfs.io/f/q1_gov_report.pdf",
    createdAt: new Date(),
  },
  {
    id: 2,
    title: "Annual Carbon Footprint Audit",
    scope: "External verification of utility logs, travel records and carbon offset calculations.",
    auditorName: "GreenTrust Auditing Solutions",
    auditDate: new Date(Date.now() + 60 * 24 * 3600 * 1000),
    status: "planned",
    findingsCount: 0,
    rating: null,
    reportUrl: null,
    createdAt: new Date(),
  },
];

export const MOCK_COMPLIANCE_ISSUES: (ComplianceIssue & { ownerName?: string })[] = [
  {
    id: 1,
    title: "Hazardous Waste Labeling Discrepancy",
    description: "Recycling drums in Warehouse B found missing updated EPA hazard warnings labels.",
    severity: "critical",
    status: "open",
    ownerId: "usr_manager",
    ownerName: "Sustainability Manager",
    dueDate: new Date(Date.now() - 5 * 24 * 3600 * 1000), // Overdue compliance item
    resolvedAt: null,
    resolvedById: null,
    createdAt: new Date(),
  },
  {
    id: 2,
    title: "Policy Acknowledgement Below Threshold",
    description: "Supplier D&I policy acknowledgements in HR are currently at 65%, which is below the target threshold of 95%.",
    severity: "medium",
    status: "open",
    ownerId: "usr_employee",
    ownerName: "Employee User",
    dueDate: new Date(Date.now() + 15 * 24 * 3650 * 1000),
    resolvedAt: null,
    resolvedById: null,
    createdAt: new Date(),
  },
  {
    id: 3,
    title: "Anti-Bribery Board Certification Overdue",
    description: "Compliance certification has not been logged for three board members.",
    severity: "high",
    status: "resolved",
    ownerId: "usr_admin",
    ownerName: "Admin User",
    dueDate: new Date(Date.now() - 10 * 24 * 3600 * 1000),
    resolvedAt: new Date(),
    resolvedById: "usr_admin",
    createdAt: new Date(),
  },
];
